// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trackly.UI.Data.DbContexts;

#nullable disable

namespace Trackly.UI.Migrations
{
    [DbContext(typeof(TracklyDbContext))]
    [Migration("20260301211119_addedTablesForReddit")]
    partial class addedTablesForReddit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Trackly.UI.Data.Models.Entitities.RedditPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubredditId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubredditId");

                    b.ToTable("RedditPosts");
                });

            modelBuilder.Entity("Trackly.UI.Data.Models.Entitities.RedditSubreddit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPostDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubredditName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubredditUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RedditSubreddits");
                });

            modelBuilder.Entity("Trackly.UI.Data.Models.Entitities.RedditPost", b =>
                {
                    b.HasOne("Trackly.UI.Data.Models.Entitities.RedditSubreddit", "Subreddit")
                        .WithMany("Posts")
                        .HasForeignKey("SubredditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subreddit");
                });

            modelBuilder.Entity("Trackly.UI.Data.Models.Entitities.RedditSubreddit", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
